[mypy]
python_version = 3.13
strict = True
warn_return_any = True
warn_unused_ignores = True
ignore_missing_imports = True

[mypy-pillow]
ignore_missing_imports = True

[mypy-PIL.*]
ignore_missing_imports = True

[mypy-pilkit.*]
ignore_missing_imports = True

[mypy-oneiric.*]
ignore_missing_imports = True

[mypy-mcp_common.*]
ignore_missing_imports = True

[mypy-fastmcp.*]
ignore_missing_imports = True

[mypy-tests.*]
disallow_untyped_defs = False
